window.HestiaReleaseConfig = {
  siteUrl: "https://hestiachat.site",
  analytics: {
    enabled: false,
    endpoint: "",
    siteId: "hestia-site",
    noticeEnabled: true,
  },
  currentVersion: "1.0.0",
  updateManifestUrl: "https://hestiachat.site/releases/latest.json",
  releasePageUrl: "https://github.com/RuslanLit/Hestia",
  releaseNotesUrl: "",
  checksumUrl: "https://hestiachat.site/releases/v1.0.0/SHA256-1.0.0.txt",
  links: {
    privacy: "privacy.html",
    comparison: "comparison.html",
    faq: "faq.html",
    source: "https://github.com/RuslanLit/Hestia",
    docs: "docs/index.html",
    serverGuide: "server-setup.html",
  },
  platforms: {
    android: {
      name: "Android arm64-v8a",
      label: "Download Android APK",
      cardLabel: "Download APK",
      fileType: "APK",
      fileName: "hestia-1.0.0-android-arm64-v8a.apk",
      fileSize: "37,576,400 bytes",
      checksum: "SHA-256 c2d4540af0574b88f6514ce1b8bbbb849c482e835eaf979a14a885e258b2ffd1",
      url: "https://hestiachat.site/releases/v1.0.0/hestia-1.0.0-android-arm64-v8a.apk",
      description: "Recommended Android APK for most current phones.",
      available: true,
    },
    androidArmv7: {
      name: "Android armeabi-v7a",
      label: "Download Android APK",
      cardLabel: "Download APK",
      fileType: "APK",
      fileName: "hestia-1.0.0-android-armeabi-v7a.apk",
      fileSize: "30,225,286 bytes",
      checksum: "SHA-256 223886ff1fd47695990d342f757021760b5f59a71f2f974dff5521d55d441c47",
      url: "https://hestiachat.site/releases/v1.0.0/hestia-1.0.0-android-armeabi-v7a.apk",
      description: "Android APK for older 32-bit ARM devices.",
      available: true,
    },
    androidX64: {
      name: "Android x86_64",
      label: "Download Android APK",
      cardLabel: "Download APK",
      fileType: "APK",
      fileName: "hestia-1.0.0-android-x86_64.apk",
      fileSize: "43,068,297 bytes",
      checksum: "SHA-256 63152c8d931a320140eda5e152db1a6630d705163eef906876f87f1a22cc509f",
      url: "https://hestiachat.site/releases/v1.0.0/hestia-1.0.0-android-x86_64.apk",
      description: "Android APK for x86_64 devices and compatible emulators.",
      available: true,
    },
    checksums: {
      name: "Checksums / SHA-256",
      label: "Download checksums",
      cardLabel: "Download checksums",
      fileType: "SHA-256 list",
      fileName: "SHA256-1.0.0.txt",
      fileSize: "371 bytes",
      checksum: "SHA-256 list for the three Android APKs",
      url: "https://hestiachat.site/releases/v1.0.0/SHA256-1.0.0.txt",
      description: "SHA-256 hashes for verifying public Android downloads.",
      available: true,
    },
    web: {
      name: "Hestia Web",
      label: "Open Hestia Web",
      cardLabel: "Coming later",
      fileType: "Web",
      fileName: "Coming later",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later.",
      available: false,
    },
    server: {
      name: "Backend for self-hosting",
      label: "Download backend",
      cardLabel: "Coming later",
      fileType: "Backend",
      fileName: "Coming later",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later.",
      available: false,
    },
    macos: {
      name: "macOS",
      label: "Download for macOS",
      cardLabel: "Coming later",
      fileType: "DMG",
      fileName: "Coming later",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later.",
      available: false,
    },
    linux: {
      name: "Linux",
      label: "Download for Linux",
      cardLabel: "Coming later",
      fileType: "AppImage / DEB / tar.gz",
      fileName: "Coming later",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later.",
      available: false,
    },
    ios: {
      name: "iOS",
      label: "iOS build",
      cardLabel: "Coming later",
      fileType: "iOS",
      fileName: "Coming later",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later.",
      available: false,
    },
  },
};
