window.HestiaReleaseConfig = {
  siteUrl: "https://hestia.example",
  analytics: {
    enabled: false,
    endpoint: "",
    siteId: "hestia-site",
    noticeEnabled: true,
  },
  currentVersion: "0.1.0-preview",
  releaseNotesUrl: "releases/0.1.0-preview.html",
  checksumUrl: "releases/0.1.0-preview-checksums.txt",
  links: {
    privacy: "privacy.html",
    comparison: "comparison.html",
    faq: "faq.html",
    source: "https://github.com/hestia-messenger",
    docs: "docs/index.html",
    serverGuide: "server-setup.html",
  },
  platforms: {
    android: {
      name: "Android",
      label: "Download for Android",
      cardLabel: "Download APK",
      fileType: "APK",
      fileName: "hestia-android-0.1.0-preview.apk",
      fileSize: "Size TBD",
      checksum: "SHA-256 TBD",
      url: "downloads/hestia-android-0.1.0-preview.apk",
      description: "Install the Android APK directly.",
    },
    windows: {
      name: "Windows",
      label: "Download for Windows",
      cardLabel: "Download for Windows",
      fileType: "EXE installer",
      fileName: "hestia-windows-0.1.0-preview.exe",
      fileSize: "Size TBD",
      checksum: "SHA-256 TBD",
      url: "downloads/hestia-windows-0.1.0-preview.exe",
      description: "Desktop installer for Windows PCs.",
    },
    macos: {
      name: "macOS",
      label: "Download for macOS",
      cardLabel: "Download for macOS",
      fileType: "DMG",
      fileName: "hestia-macos-0.1.0-preview.dmg",
      fileSize: "Size TBD",
      checksum: "SHA-256 TBD",
      url: "downloads/hestia-macos-0.1.0-preview.dmg",
      description: "Desktop package for Mac devices.",
    },
    linux: {
      name: "Linux",
      label: "Download for Linux",
      cardLabel: "Download for Linux",
      fileType: "AppImage",
      fileName: "hestia-linux-0.1.0-preview.AppImage",
      fileSize: "Size TBD",
      checksum: "SHA-256 TBD",
      url: "downloads/hestia-linux-0.1.0-preview.AppImage",
      description: "Portable desktop build for Linux systems.",
    },
    web: {
      name: "Web",
      label: "Open Web Version",
      cardLabel: "Open Web Version",
      fileType: "Browser app",
      fileName: "Web client",
      fileSize: "No download",
      checksum: "Not applicable",
      url: "https://app.hestia.example",
      description: "Use Hestia in a modern browser.",
    },
    server: {
      name: "Self-hosted server",
      label: "Self-host your server",
      cardLabel: "Server setup guide",
      fileType: "Guide",
      fileName: "server-setup.html",
      fileSize: "Documentation",
      checksum: "Not applicable",
      url: "server-setup.html",
      description: "Prepare your own Hestia backend when you want infrastructure control.",
    },
  },
};
