window.HestiaReleaseConfig = {
  siteUrl: "https://hestiachat.site",
  analytics: {
    enabled: false,
    endpoint: "",
    siteId: "hestia-site",
    noticeEnabled: true,
  },
  currentVersion: "4.0.0_1",
  updateManifestUrl: "https://hestiachat.site/releases/latest.json",
  releasePageUrl: "https://github.com/RuslanLit/Hestia/releases/tag/v4.0.0_1",
  releaseNotesUrl: "https://github.com/RuslanLit/Hestia/releases/tag/v4.0.0_1",
  checksumUrl: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/4.0.0-checksums.txt",
  links: {
    privacy: "privacy.html",
    comparison: "comparison.html",
    faq: "faq.html",
    source: "https://github.com/RuslanLit/Hestia",
    docs: "docs/index.html",
    serverGuide: "server-setup.html",
  },
  platforms: {
    android: {
      name: "Android",
      label: "Download for Android",
      cardLabel: "Download APK",
      fileType: "APK",
      fileName: "hestia-4.0.0_1-android.apk",
      fileSize: "92.33 MB",
      checksum: "SHA-256 47932f8b404c6237c472911dfdf67d72160e0028f304c20f3a68aa72b0ab694f",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-android.apk",
      description: "Install the Android APK directly.",
      available: true,
    },
    windows: {
      name: "Windows",
      label: "Download for Windows",
      cardLabel: "Download for Windows",
      fileType: "EXE installer",
      fileName: "hestia-4.0.0_1-windows-setup.exe",
      fileSize: "23.64 MB",
      checksum: "SHA-256 7afc08f52ddcfaecdfbda197512bd6681b94b7af0fdb7a0304dd1909df0c1033",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-windows-setup.exe",
      description: "Desktop installer for Windows PCs.",
      available: true,
    },
    windowsPortable: {
      name: "Windows portable",
      label: "Download portable ZIP",
      cardLabel: "Download ZIP",
      fileType: "Portable ZIP",
      fileName: "hestia-4.0.0_1-windows-portable.zip",
      fileSize: "23.63 MB",
      checksum: "SHA-256 099d97583ccf32663beb5dd2ea9366e4dd0d935ca7de13a918abd23e2a4cb818",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-windows-portable.zip",
      description: "Portable Windows package without an installer.",
      available: true,
    },
    macos: {
      name: "macOS",
      label: "Download for macOS",
      cardLabel: "Download for macOS",
      fileType: "DMG",
      fileName: "Not available",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later. Requires a macOS build environment; unsigned builds may show Gatekeeper warnings.",
      available: false,
    },
    linux: {
      name: "Linux",
      label: "Download for Linux",
      cardLabel: "Download for Linux",
      fileType: "AppImage / DEB / tar.gz",
      fileName: "Not available",
      fileSize: "Coming later",
      checksum: "Not available",
      url: "",
      description: "Coming later. Requires a Linux Flutter build environment.",
      available: false,
    },
    ios: {
      name: "iOS",
      label: "iOS build",
      cardLabel: "Not available",
      fileType: "iOS",
      fileName: "Not available",
      fileSize: "Not available",
      checksum: "Not available",
      url: "",
      description: "Not available without Apple Developer Program signing and distribution.",
      available: false,
    },
    web: {
      name: "Web",
      label: "Download web static build",
      cardLabel: "Download web ZIP",
      fileType: "Static ZIP",
      fileName: "hestia-4.0.0_1-web-static.zip",
      fileSize: "13.50 MB",
      checksum: "SHA-256 5eb2be36882d8dd941a2b5b3b02b4e12354887d2e09135ece48711abdfac97f2",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-web-static.zip",
      description: "Static web client bundle for hosting.",
      available: true,
    },
    server: {
      name: "Self-hosted server",
      label: "Download backend server",
      cardLabel: "Download backend",
      fileType: "Backend ZIP",
      fileName: "hestia-4.0.0_1-backend.zip",
      fileSize: "31.18 KB",
      checksum: "SHA-256 ee376597fd98b584708462ea0143f5fe016f81d128394ba2220850cf74098b8b",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-backend.zip",
      description: "Backend server package for self-hosting.",
      available: true,
    },
    landing: {
      name: "Landing/site package",
      label: "Download landing site",
      cardLabel: "Download site ZIP",
      fileType: "Static site ZIP",
      fileName: "hestia-4.0.0_1-landing.zip",
      fileSize: "2.35 MB",
      checksum: "See checksums file",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/hestia-4.0.0_1-landing.zip",
      description: "Static landing/site package for deployment.",
      available: true,
    },
    checksums: {
      name: "Checksums",
      label: "Download checksums",
      cardLabel: "Download checksums",
      fileType: "SHA-256 list",
      fileName: "4.0.0-checksums.txt",
      fileSize: "582 B",
      checksum: "Verified by GitHub asset digest",
      url: "https://github.com/RuslanLit/Hestia/releases/download/v4.0.0_1/4.0.0-checksums.txt",
      description: "SHA-256 hashes for verifying release files.",
      available: true,
    },
  },
};
